
baseURL = "http://atiavda_one/"
languageCode = "en-gb"
title = "atiavda.one"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

DefaultContentLanguage = "en"
enableRobotsTXT = true
Paginate = 3 # required
SectionPagesMenu = "main"

[languages]
  [languages.en]
    title = "atiavda.one"
    weight = 1
    contentDir = "content/en"
  [languages.fr]
    title = "atiavda.one Fr"
    weight = 2
    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Jo"
  favicon = ""
  site_logo = ""
  description = "Healthy living, reaching for the divine, joy!"
  background_color_class = "bg-orange"  # https://tachyons.io/docs/themes/skins/
  recent_posts_number = 3

